# Generated by Django 3.0.4 on 2022-10-21 04:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customBuildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color_code', models.CharField(blank=True, max_length=10, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.CharField(max_length=50)),
                ('default_metric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('use_area', models.BooleanField(default=False)),
                ('cost_per_area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('amenity', models.CharField(blank=True, max_length=50, null=True)),
                ('building_levels', models.IntegerField(default=1)),
                ('building_outline', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingDmgVun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damaged_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_attributes', to='customBuildings.Building')),
                ('damaged_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buildings_with_attributes', to='customBuildings.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_with_type', to='customBuildings.AttributeType'),
        ),
    ]
