# Generated by Django 3.0.4 on 2023-01-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customBuildings', '0002_auto_20221021_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='osm_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
