# Generated by Django 3.0.4 on 2023-01-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customBuildings', '0003_auto_20230111_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdmgvun',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
